### ISSUE TITLE
gen agent use this tool not  success

### ISSUE THREAD

**Issue by cmxhbut** [hellovimo/uvm_testbench_gen#1]
hi，
 i use the tools in GUI mode, and want to gen a agent，it always report sequence_item have exit, and use os.replace function exist problem ,do you know why?

**Comment by hellovimo** [comment]
Hello @cmxhbut , Few questions regarding your issue:
1. First are you running the tool in windows or linux ? Best case would be to run the tool in linux.  
2. Did you try creating just the agent using the "Create single component" mode ? or via "Complete UVM VIP" ?
3. If its single component, after selecting the agent - did you enter the required number, name of the drivers, monitors you wanted to create ?
4. Also can you run the script with debug enabled when you tried creating ? To see what is getting printed in the dbg.log file. 
Please let me know. Thanks.

**Comment by ninipa** [comment]
Hi,

I think I met the same issue. Then I found maybe the GUI desscription and figure4 in "https://github.com/hellovimo/uvm_testbench_gen/wiki/Detailed-Tool-Operation-For-Generating-Single-UVM-Component-Object" should be updated.
If you just enter the number of driver/monitor, the issue will be reported; if you enter as "1, drv", it's OK.
